### ISSUE TITLE
Site-configuratie moet makkelijker/duidelijker zijn

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/gemma-documentregistratiecomponent#35]
Nu is er de (verborgen) `IS_HTTPS` envvar die gebruikt wordt om interne URLs op te bouwen buiten de request-response cycle. Het zou handig zijn als dit op de site (in de DB) kan geconfigureerd worden.

Verder is getting-started documentatie wel handig om het onboarden te versoepelen.

(cc/ @bartjkdp)

**Comment by sergei-maertens** [comment]
@bartjkdp is geland in huidige develop, en de docs worden meegepubliceerd in de Docker image

**Comment by bartjkdp** [comment]
Thanks @sergei-maertens !!
