### ISSUE TITLE
404 Client Error bij verzoek naar ZRC voor informatieobjecten

### ISSUE THREAD

**Issue by bartjkdp** [VNG-Realisatie/gemma-documentregistratiecomponent#40]
Ik probeer een nieuwe Melding Openbare Ruimte toe te voegen met de [gemma-zaken-demo](https://www.github.com/vng-realisatie/gemma-zaken-demo) applicatie. Het werkt prima zonder bijlage, maar met bijlage krijg ik de volgende foutmelding op de demo applicatie:

![image](https://user-images.githubusercontent.com/5213690/53748202-29017c80-3ea5-11e9-8ae3-17373650e74c.png)

Verzoek / antwoord ziet er als volgt uit:

![image](https://user-images.githubusercontent.com/5213690/53748246-3fa7d380-3ea5-11e9-9ee3-a515a0a95118.png)

![image](https://user-images.githubusercontent.com/5213690/53748262-4afaff00-3ea5-11e9-840b-289cc5fa0a04.png)

Wanneer ik handmatig in de admin van gemma-drc een `objectinformatieobject` probeer aan te maken dan krijg ik ook de foutmelding: "Could not create remote relation":

![image](https://user-images.githubusercontent.com/5213690/53748284-564e2a80-3ea5-11e9-8546-771a03c009aa.png)

Het interessante is dat in de stack trace de volgende foutmelding staat:

![image](https://user-images.githubusercontent.com/5213690/53748393-91e8f480-3ea5-11e9-8166-3f6d2e9814a8.png)

Let met name op de dubbel slash: `/api/v1//zaken/...`, dat klopt inderdaad niet, hier krijg ik ook een 404 op. Met enkele slash kan ik de URL vanuit mijn browser benaderen.

Wat meer stack trace:

![image](https://user-images.githubusercontent.com/5213690/53748471-ae852c80-3ea5-11e9-849f-113523ad8a53.png)

Waar komt deze dubbele slash vandaan?

**Comment by sergei-maertens** [comment]
Root fix in https://github.com/VNG-Realisatie/gemma-zds-client/commit/9ecd190cdf80fd6d4c7bea8c658c473383753db5

zds-schema fix in https://github.com/VNG-Realisatie/gemma-zaken-common/commit/5fe2b3a74a8236ceed61f66ce45964ef0a9a616c (requires minimum version of `gemma-zds-client==0.9.3`)
